# setup workflows ##
version: 2.1

# denotes that it is setup workflow
setup: true

#            HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" -X GET https://runner.circleci.com/api/v2/tasks?resource-class=test_runner/m1Pro
#              -H 'Circle-Token: "${RUNNER_API_TOKEN}"')

jobs:
  check_queue_depth:
    docker:
      - image: cimg/base:2022.03
    steps:
      - run:
          command: |
            if [ -z "${RUNNER_API_TOKEN}" ]; then
              echo "RUNNER_API_TOKEN is required. Make sure this is defined in Project Settings."
              exit 1
            fi
            
            if ! which curl > /dev/null; then
               echo "curl is required to use this command"
               exit 1
            fi
            
            if ! which jq > /dev/null; then
               echo "jq is required to use this command"
               exit 1
            fi
                     
            HTTP_RESPONSE=$(curl -f -s -X GET -H "Circle-Token:${RUNNER_API_TOKEN}" --write-out "HTTPSTATUS:%{http_code}" "https://runner.circleci.com/api/v2/tasks?resource-class=test_runner/m1Pro")         
            
            HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
            
            if [ $http_response != "200" ]; then
              echo "ERROR: Server returned error code: $http_response"
              exit 1
            else
              echo "DEBUG: API Success"
            fi
            
            echo "$HTTP_RESPONSE"
            echo "$HTTP_BODY"
            
            UNCLAIMED_TASK_COUNT=$(echo $HTTP_BODY | jq ".unclaimed_task_count")
            
            echo "$UNCLAIMED_TASK_COUNT"
            
            
            
            

  test_runner:
    machine: true
    resource_class: test_runner/m1Pro
    steps:
      - run: echo "Hi I'm on Runners!"

workflows:
   main:
    jobs:
      - check_queue_depth